// Generated by CoffeeScript 1.6.2
var StylusCompiler, exec, fs, nib, spawn, sprite, stylus, sysPath, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

_ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

nib = require('nib');

fs = require('fs');

stylus = require('stylus');

sysPath = require('path');

sprite = require('node-sprite');

module.exports = StylusCompiler = (function() {
  StylusCompiler.prototype.brunchPlugin = true;

  StylusCompiler.prototype.type = 'stylesheet';

  StylusCompiler.prototype.extension = 'styl';

  StylusCompiler.prototype._dependencyRegExp = /^ *@import ['"](.*)['"]/;

  function StylusCompiler(config) {
    var _base, _base1, _ref1, _ref2, _ref3, _ref4, _ref5,
      _this = this;

    this.config = config;
    this.getDependencies = __bind(this.getDependencies, this);
    this.getCompiler = __bind(this.getCompiler, this);
    this.compile = __bind(this.compile, this);
    if ((_ref1 = (_base = this.config).plugins) == null) {
      _base.plugins = {};
    }
    if (this.config.stylus) {
      console.warn("Warning: config.stylus is deprecated, move it to config.plugins.stylus");
      if ((_ref2 = (_base1 = this.config.plugins).stylus) == null) {
        _base1.stylus = this.config.stylus;
      }
    }
    if ((_ref3 = this.config.plugins) != null ? (_ref4 = _ref3.stylus) != null ? _ref4.spriting : void 0 : void 0) {
      this.iconPath = (_ref5 = this.config.plugins.stylus.iconPath) != null ? _ref5 : sysPath.join('images', 'icons');
      this.iconPathFull = sysPath.join(this.config.paths.assets, this.iconPath);
      if (!fs.existsSync(this.iconPathFull)) {
        console.error("Please make sure that the icon path " + this.iconpath + " exits");
      }
      exec('convert --version', function(error, stdout, stderr) {
        if (error) {
          return console.error("You need to have convert (ImageMagick) on your system for spriting");
        }
      });
    }
    null;
  }

  StylusCompiler.prototype.compile = function(data, path, callback) {
    var _this = this;

    return this.getCompiler(data, function(compiler) {
      var defines, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;

      compiler = compiler.set('filename', path).set('compress', false).set('firebug', !!((_ref3 = _this.config.plugins) != null ? (_ref4 = _ref3.stylus) != null ? _ref4.firebug : void 0 : void 0)).set('linenos', !!((_ref1 = _this.config.plugins) != null ? (_ref2 = _ref1.stylus) != null ? _ref2.linenos : void 0 : void 0)).include(sysPath.join(_this.config.paths.root)).include(sysPath.dirname(path)).use(nib());
      if ((_ref5 = _this.config.plugins) != null ? _ref5.stylus : void 0) {
        defines = (_ref6 = _this.config.plugins.stylus.defines) != null ? _ref6 : {};
        Object.keys(defines).forEach(function(name) {
          return compiler.define(name, defines[name]);
        });
        if ((_ref7 = _this.config.plugins.stylus.paths) != null) {
          _ref7.forEach(function(path) {
            return compiler.include(path);
          });
        }
      }
      return compiler.render(callback);
    });
  };

  StylusCompiler.prototype.getCompiler = function(data, callback) {
    var options, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6,
      _this = this;

    if ((_ref1 = this.config.plugins) != null ? (_ref2 = _ref1.stylus) != null ? _ref2.spriting : void 0 : void 0) {
      options = {
        path: ((_ref3 = this.config.plugins.stylus.options) != null ? _ref3.path : void 0) || this.iconPathFull,
        retina: ((_ref4 = this.config.plugins.stylus.options) != null ? _ref4.retina : void 0) || '-2x',
        padding: ((_ref5 = this.config.plugins.stylus.options) != null ? _ref5.padding : void 0) || 2,
        httpPath: ((_ref6 = this.config.plugins.stylus.options) != null ? _ref6.httpPath : void 0) || '../' + this.iconPath
      };
      return sprite.stylus(options, function(err, helper) {
        return callback(stylus(data).define('sprite', helper.fn));
      });
    } else {
      return callback(stylus(data));
    }
  };

  StylusCompiler.prototype.getDependencies = function(data, path, callback) {
    var dependencies, parent,
      _this = this;

    parent = sysPath.dirname(path);
    dependencies = data.split('\n').map(function(line) {
      return line.match(_this._dependencyRegExp);
    }).filter(function(match) {
      return (match != null ? match.length : void 0) > 0;
    }).map(function(match) {
      return match[1];
    }).filter(function(path) {
      return !!path && path !== 'nib';
    }).map(function(path) {
      if (sysPath.extname(path) !== ("." + _this.extension)) {
        return path + ("." + _this.extension);
      } else {
        return path;
      }
    }).map(function(path) {
      if (path.charAt(0) === '/') {
        return sysPath.join(_this.config.paths.root, path.slice(1));
      } else {
        return sysPath.join(parent, path);
      }
    });
    return process.nextTick(function() {
      return callback(null, dependencies);
    });
  };

  return StylusCompiler;

})();
